### ISSUE TITLE
feat: MediaLayerManager

### ISSUE THREAD

**Issue by und3fined-v01d** [und3fined-v01d/webxr-layers#17]
## Description

Implement a standard interface to handle creation of medialayers and binding toolbars to those layers

**Comment by zhixiangteoh** [comment]
https://lucid.app/lucidchart/invitations/accept/1b384b13-cff1-457f-89d2-b01eedb98657

![17-MediaLayerManager](https://user-images.githubusercontent.com/47135468/109681807-ce48ab80-7bb8-11eb-9f54-c256ef29aea7.png)

Very rough, tentative diagram. LMK if anything seems off, we will continuously tweak it as we go along.
